#!/usr/bin/env bash
# Deploy the Alliance proposal page to the Cloudflare Worker `alliance-proposal`
# (custom domain: alliance.sitech.ge).
#
# Source of truth is ../index.html, generated by tools/build-page.py from the frozen copy in
# shared-knowledge/projects/edo-portfolio/CONTENT-alliance-ka.md. Only that one file is
# published: it is staged into a throwaway directory (site/) next to a minimal wrangler
# config, so the worker never serves tools/, evidence/, delivery/ or its own config.
# workers_dev / preview_urls are off on purpose: alliance.sitech.ge is the single public origin.
#
# Usage: CLOUDFLARE_API_TOKEN=... bash alliance/tools/deploy.sh
set -euo pipefail
cd "$(dirname "$0")/.."          # alliance/

: "${CLOUDFLARE_API_TOKEN:?export CLOUDFLARE_API_TOKEN first}"

if [ ! -f index.html ]; then
  echo "index.html not found in $(pwd) — run tools/build-page.py first" >&2
  exit 1
fi

STAGE=.deploy
rm -rf "$STAGE"; mkdir -p "$STAGE/site"
cp -f index.html "$STAGE/site/index.html"
cat > "$STAGE/wrangler.jsonc" <<'JSON'
{
  "name": "alliance-proposal",
  "compatibility_date": "2026-09-29",
  "workers_dev": false,
  "preview_urls": false,
  "assets": {
    "directory": "./site",
    "html_handling": "auto-trailing-slash",
    "not_found_handling": "404-page"
  }
}
JSON
( cd "$STAGE" && npx --yes wrangler deploy )
rm -rf "$STAGE"
